<?php $categories = $block->getCategoryList(); ?>
<div class="subCat-section">
    <div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="insd-subCat">
					<ul>
						<?php foreach ($categories as $category): ?>
							<?php if ($category['image']): ?>
							<li><a href="<?php echo $category->getUrl() ?>"  title="<?php echo $category->getName() ?>">
									
										<img src="<?php echo $block->getCategoryThumbImage($category['image']); ?>" />
									<?php //else: ?>
										<!--<img src="<?php //echo $block->getViewFileUrl($block->getPlaceholderImage()); ?>" />-->
									
								</a>
								<div class="subCat-txt">
									<h3><?php echo $category->getName() ?></h3>
									<a href="<?php echo $category->getUrl() ?>"><?php echo 'View All'; ?></a>
								</div>
							</li>
							<?php endif; ?>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>
		</div>
    </div>
</div>