<?php 
echo "<pre>";
print_r($block->getActiveFilters());
?>

	<ul class="sub-cat">
	<?php
//	$i = 0;
	//	foreach ($subcats as $subcat) {
	//		$_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
	//		$_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
	//		$subcaturl = $subcat->getUrl();
	?>
	<?php 
	//	$active = '';
	//	if($i ==0) {
	//		$active = 'active';
	//	}
	?>
		<li class="<?php //echo $active; ?>">
			<div class="info">
				<a class="link" href="<?php //echo $subcaturl ?>"><?php //echo //$subcat->getName(); ?></a></div>
		</li>
	<?php  //$i++; } ?>
	</ul>