   <!-- featured_sec start -->
   <section class="featured_sec">
      <div class="container">
         <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

               <h1>Featured Products</h1>

               <div class="insdFeatured">

                  <div class="featBlock">
                     <div class="imgSec">
                        <p>Choose from one of our popular templates for your brand and industry.  We make it easy to order so you can impress your clients and still get back to doing what you do best during your busy day.  Whether its full color with coating, raised printing or foil accents, we're here to help you put your best foot forward.</p>
                        <a href="#">See More</a>
                       <img src='<?php echo $this->getViewFileUrl('Synapse_Custom::images/thumb1.jpg'); ?>' alt="image-icon">
                     </div>

                     <div class="txt">
                        <h2>Business Cards</h2>
                     </div>
                  </div>


                  <div class="featBlock">
                     <div class="imgSec">
                        <p>Want to keep your name in front of your customer longer? Turn your full color business card design into a long term advertising billboard on your client's fridge.
						</p>
                        <a href="#">See More</a>
                         <img src='<?php echo $this->getViewFileUrl('Synapse_Custom::images/thumb2.jpg'); ?>' alt="image-icon">
                     </div>

                     <div class="txt">
                        <h2>Magnetic Cards</h2>
                     </div>
                  </div>


                  <div class="featBlock">
                     <div class="imgSec">
                        <p>The most cost effective way to reach your customers thru the US mail.Available in full color.</p>
                        <a href="#">See More</a>
                        <img src='<?php echo $this->getViewFileUrl('Synapse_Custom::images/thumb3.jpg'); ?>' alt="image-icon">
                     </div>

                     <div class="txt">
                        <h2>Post Cards</h2>
                     </div>
                  </div>


                  <div class="featBlock">
                     <div class="imgSec">
                        <p>A professional letter in today's mail helps you cut through the email clutter.  We'll help you create professional stationery that you'll be proud to use for years to come.</p>
                        <a href="#">See More</a>
                       <img src='<?php echo $this->getViewFileUrl('Synapse_Custom::images/thumb4.jpg'); ?>' alt="image-icon">
                     </div>

                     <div class="txt">
                        <h2>Stationery</h2>
                     </div>
                  </div>

                  <div class="featBlock">
                     <div class="imgSec">
                        <p>Whether you're sending in the mail, leaving on the prospect's counter or trade show booth, a full color brochure can help augment your message on your way to make the sale.</p>
                        <a href="#">See More</a>
                       <img src='<?php echo $this->getViewFileUrl('Synapse_Custom::images/thumb5.jpg'); ?>' alt="image-icon">
                     </div>

                     <div class="txt">
                        <h2>Bi-Folds & Tri-Folds, Flyers &
                           Brochures</h2>
                     </div>
                  </div>


                  <div class="featBlock">
                     <div class="imgSec">
                        <p>Save time and enhance your image among your clients, and customers alike with commercial envelopes.  They're a great value and a regular office staple.  If you're buying our cards, then you'll want to ask about commercial envelopes too.</p>
                        <a href="#">See More</a>
                        <img src='<?php echo $this->getViewFileUrl('Synapse_Custom::images/thumb6.jpg'); ?>' alt="image-icon">
                     </div>

                     <div class="txt">
                        <h2>Commercial Envelopes</h2>
                     </div>
                  </div>


                  <div class="featBlock">
                     <div class="imgSec">
                        <p>Wind and Highway proof, you'll love our car magnets.</p>
                        <a href="#">See More</a>
                       <img src='<?php echo $this->getViewFileUrl('Synapse_Custom::images/thumb7.jpg'); ?>' alt="image-icon">
                     </div>

                     <div class="txt">
                        <h2>car magnetS</h2>
                     </div>
                  </div>

                  <div class="featBlock">
                     <div class="imgSec">
                        <p>Whether its about the house for sale or your political advertising campaign, let us help you with your yard signs.</p>
                        <a href="#">See More</a>
                        <img src='<?php echo $this->getViewFileUrl('Synapse_Custom::images/thumb8.jpg'); ?>' alt="image-icon">
                     </div>

                     <div class="txt">
                        <h2>Yard Signs</h2>
                     </div>
                  </div>


                  <div class="featBlock">
                     <div class="imgSec">
                        <p> 2 to 5 parts in standard and custom sizes glued in sets, we can pad them and/or number them.  Carbonless forms are the backbone to some of the best organizations worldwide.  Let us help you with this important office staple because we've got the expertise.</p>
                        <a href="#">See More</a>
                       <img src='<?php echo $this->getViewFileUrl('Synapse_Custom::images/thumb9.jpg'); ?>' alt="image-icon">
                     </div>

                     <div class="txt">
                        <h2>Carbonless formS</h2>
                     </div>
                  </div>

               </div>

            </div>
         </div>
      </div>
   </section>
   <!-- featured_sec end -->



   <!-- why box start -->
   
   <!-- why box end -->