<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css" rel="stylesheet" />


<script>
    require([
        'jquery',
        'select2'
    ], function ($) {
        'use strict';

        console.log('SK YDAVAV Called');
       // $("#customer_company").multiselect2({});
/*
        var country = ["Australia", "Bangladesh", "Denmark", "Hong Kong", "Indonesia", "Netherlands", "New Zealand", "South Africa"];
            $("#customer_company").select2({
              data: country
            }); */
            setTimeout(function(){
               $('select[name="product[customer_company]"]').select2();
            },3000)
      
            

    });
</script>
