<?php 
$blockObj= $block->getLayout()->createBlock('Synapse\Custom\Block\Adminhtml\Pdf\Item');

$customCard = 0;

if( $block->getItem()->getData('json_card') ||  $block->getItem()->getData('json_card_back')) {
	$customCard = 1;	
}

$item_id = $block->getItem()->getData('item_id');
$itemUrl = $blockObj->getPdfUrl($item_id);
$designimageurl = $blockObj->getDesignimageUrl($item_id);
?>
<?php if($customCard ) { ?>
	<a href ="<?php echo $this->getUrl($itemUrl); ?>" target="_blank" class="item_pdf">Print PDF</a>
	|
	<a href ="<?php echo $this->getUrl($designimageurl); ?>" target="_blank" class="item_image">Review Card</a>
<?php } ?>