<?php 
$order_itemdata = $block->getOrderData();
$additional_options = $order_itemdata->getProductOptions()['additional_options'];
 if(isset($additional_options['cardtype']) && $additional_options['cardtype']=='Rounded'){
	 $card_type = 2;
 }else{
	 $card_type = 1;
 }
$frontJson 	= $order_itemdata->getJsonCard();
$backJson 	= $order_itemdata->getJsonCardBack();
$decoded_backjson = json_decode($backJson,true);
$objarr = $decoded_backjson['objects'];
$showbackend = false; 
if(is_array($objarr) && count($objarr)>0){
	$showbackend = true;
}
$params  = $this->getPost();
if(isset($params['item_id'])) {
	$item_id = $params['item_id'];
}else{
	$item_id ='';
}
?>

<input type="hidden" id="item_id" value='<?php echo $item_id; ?>'>
<input type="hidden" id="adminurl" value='<?php echo $this->getUrl('designimage/designimage/save'); ?>'>

<div id="canvasID" class="review-card">
	<div id="safe-zone-inicator">
		<p style="text-align: center; font-size: 18px;"></p>
	</div>
	<div id="admin-view" class="card-design-wrapper for-admin-use">
		<div class="container">
			<div class="card-main-option">
				<div class="logo">Business cards - standard matte</div>
				<div class="mobile-menu">
					<div class="trigger_box">
						<i class="fa fa-bars" aria-hidden="true"></i>
						<i class="fa fa-times" aria-hidden="true"></i>
					</div>
				</div>
			</div>
			<div class="card-editing-area-wrapper">
				<?php if($frontJson) { ?>
					<input type="hidden" name="admin_card_front" id="admin_card_front" value ='<?php echo $frontJson; ?>' />
				<?php 
				}
				if($showbackend) { ?>
					<input type="hidden" name="admin_card_back" id="admin_card_back" value ='<?php echo json_encode($decoded_backjson); ?>' />
				<?php } ?>
							
				<div class="card-editing-area-wrapper-left">
					<div class="card-editing-tabs user-card-editing-area" id="text-edit" style="display: block;">
						<input type="text" value="Tap & Type" id="updateValue" hidden>					
						<div class="user-front-card-wrapper canvas-edit" id="export_front">

							<div class="front-inputs-ctrl" id="user-text-exprt"></div>
						</div>
						<div class="user-back-card-wrapper  canvas-edit-back" id="export_back">
							<div class="back-inputs-ctrl"></div>
						</div>
					</div>
					<div class="card-editing-tabs" id="image-edit">
						<div class="card-background-image">
							<input type="file" class="custom-file-input canvas-bg-image" id="file2">
							<span class="card-image-text">Upload Background Image</span>
						</div>
						<div class="card-logo-image">
							<input type="file" class="custom-file-input canvas-logo-image" id="file">
							<span class="card-image-text">Upload Image</span>
						</div>
					</div>
					<div class="card-editing-tabs" id="image-edit-back">
						<div class="backPannel">
							<div class="backCardContent">
								<div class="backView">
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="card-editing-area-wrapper-right">
					<div class="canvas-wrapper" id="front-view">
						<div id="left-scale-h" class="top_scale"></div>
						<div id="top-scale-v" class="left_scale"></div>
						<div class="bg-img"></div>
						<div class="safe-zone"></div>
						<canvas id="front" onkeydown='getKeyAndMove(event)' tabindex="0"></canvas>
					</div>
					<?php// if($showbackend) { ?>
					<div class="canvas-wrapper" id="back-view">
						<div id="back-left-scale-h" class="top_scale"></div>
						<div id="back-top-scale-v" class="left_scale"></div>
						<div class="bg-img"></div>
						<div class="safe-zone"></div>
						<canvas id="backcanvas"></canvas>
					</div>
					<?php// } ?>
					<div class="canvas-editing-options ui-widget-content" id="textEditOptions">
						<div class="image-drag">
							<img src="images/drag-icon.png">
						</div>
						<div class="canvas-editing-options-top">
							<div class="top-slide-container" id="font-family">
								<ul id="font-family-list"></ul>
							</div>
							<div class="top-slide-container" id="font-size">
								<label for="">Font Size</label>
								<input type="text" value="20" class="fontSizeInputVal">
								<input type="range" min="20" max="100" value="20" class="fontSizeRangeVal slider">
							</div>
							<div class="top-slide-container" id="text-color">
								<input type="text" id="colorpicker-full" class="color-pick" value="000000">
							</div>
							<div class="top-slide-container" id="text-shadow">
								<input type="text" id="colorpicker-shadow" class="color-pick" value="ff0000">
								<div class="shadow-control">
									<label for="">Blur:<input type="range" min="-10" max="10" value="1"
											class="blur-shadow slider"></label>
									<label for="">offsetX:<input type="range" min="-10" max="10" value="-4"
											class="offsetX-shadow slider"></label>
									<label for="">offsetY:<input type="range" min="-10" max="10" value="3"
											class="offsetY-shadow slider"></label>
								</div>
							</div>
							<div class="top-slide-container" id="text-outline">
								<input type="text" id="colorpicker-outline" class="color-pick" value="ff0000">
								<input type="range" min="0" max="5" value="1" class="text-outline-slider slider">
							</div>
							<div class="top-slide-container" id="line-height">
								<label for="">Line Height</label>
								<input type="text" value="1.16" class="lineHeightInputVal">
								<input type="range" min="1" max="2" value="1.16" step="0.03"
									class="lineHeightRangeVal slider">
							</div>
							<div class="top-slide-container" id="letter-spacing">
								<label for="">Letter Spacing</label>
								<input type="text" value="1.16" class="letterSpacingInputVal">
								<input type="range" min="0" max="400" value="0" step="5"
									class="letterSpacingRangeVal slider">
							</div>
							<div class="more-slide">
								<ul>
									<li>
										<a title="Font Family" href="javascript: void(0)" class="font-family">Arial</a>
									</li>
									<li>
										<a title="Font Size" href="javascript: void(0)" class="font-size">20</a>
									</li>
									<li>
										<a title="Line Height" href="javascript: void(0)" class="line-height">1.16</a>
									</li>
									<li>
										<a title="Letter Spacing" href="javascript: void(0)"
											class="letter-spacing">0</a>
									</li>
									<li>
										<a href="javascript: void(0)" class="text-color">Color</a>
									</li>
									<li>
										<a href="javascript: void(0)" class="slide-for-more">More <i
												class="fa fa-chevron-right" aria-hidden="true"></i></a>
									</li>
									<li>
										<a href="javascript: void(0)" class="slide-for-less">
											<i class="fa fa-chevron-left" aria-hidden="true"></i>
										</a>
									</li>
									<li>
										<a title="Bold" href="javascript: void(0)" class="bold-font">
											<i class="fa fa-bold"></i>
										</a>
									</li>
									<li>
										<a title="Underline" href="javascript: void(0)" class="underline-font"><i
												class="fa fa-underline"></i></a>
									</li>
									<li>
										<a title="Italic" href="javascript: void(0)" class="italic-font">
											<i class="fa fa-italic"></i>
										</a>
									</li>
									<li>
										<a title="Delete" href="javascript: void(0)" class="delete-object">
											<i class="fa fa-trash"></i></a>
									</li>
									<li>
										<a title="Align Left" href="javascript: void(0)" class="align-left">
											<i class="fa fa-align-left"></i>
										</a>
									</li>
									<li>
										<a title="Align Center" href="javascript: void(0)" class="align-center">
											<i class="fa fa-align-center"></i>
										</a>
									</li>
									<li>
										<a title="Align Right" href="javascript: void(0)" class="align-right">
											<i class="fa fa-align-right"></i>
										</a>
									</li>
									<li>
										<a title="Duplicate" href="javascript: void(0)" class="dublicate-copy">
											<i class="fa fa-copy"></i>
										</a>
									</li>
									<li>
										<a title="Arrange" href="javascript: void(0)" class="arrange-object">
											<i class="fa fa-layer-group"></i>
										</a>
									</li>
									<li>
										<a title="Rotate" href="javascript: void(0)" class="rotate-object">
											<i class="fa fa-repeat"></i>
										</a>
									</li>
									<li>
										<a title="Text Shadow" href="javascript: void(0)" class="text-shadow">A</a>
									</li>
									<li>
										<a title="Text Outline" href="javascript: void(0)" class="text-outline"><img
												src="images/text-outline.png" alt=""></a>
									</li>
								</ul>
							</div>
						</div>
						<div class="canvas-editing-options-bottom">
							<textarea class="inputVal">Enter Text Here</textarea>
						</div>
					</div>
					<div class="canvas-editing-options ui-widget-content" id="imageEditOptions">
						<div class="top-slide-container" id="replace-object">
							<div class="card-logo-image">
								<input type="file" class="custom-file-input canvas-logo-image" id="fileReplace">
								<span class="card-image-text">Upload Image</span>
							</div>
						</div>
						<div class="top-slide-container" id="text-color-image">
							<div class="color-filter">
								<label for="">Color</label>
								<input type="range" class="image-filter-color slider">
								<a href="javascript: void(0)" class="reset-image-filter-color">Reset</a>
							</div>
							<div class="color-filter">
								<label for="">Saturation</label>
								<input type="range" class="image-filter-saturation slider" value="0.1" min="0" max="1"
									step="0.003921">
								<a href="javascript: void(0)" class="reset-image-filter-saturation">Reset</a>
							</div>
							<div class="color-filter">
								<label for="">Lightness</label>
								<input type="range" class="slider image-filter-lightness" value="0.1" min="-1" max="1"
									step="0.003921">
								<a href="javascript: void(0)" class="reset-image-filter-lightness">Reset</a>
							</div>
						</div>

						<div class="top-slide-container" id="arrange-object">
							<div class="bring-front col-arrange">
								<a href="javascript: void(0)" class="b2f">Bring to Front</a>
								<a href="javascript: void(0)" class="bf">Bring Forward</a>
							</div>
							<div class="bring-back col-arrange">
								<a href="javascript: void(0)" class="s2b">Send to Back</a>
								<a href="javascript: void(0)" class="sb">Send Backward</a>
							</div>
						</div>

						<div class="canvas-editing-options-top">
							<div class="more-slide">
								<ul>
									<li>
										<a href="javascript: void(0)" class="love-move-object lock">
											<i class="fa fa-lock" aria-hidden="true"></i>
											<i class="fa fa-arrows" aria-hidden="true"></i>
											<span class="moreslide-text lock">Lock</span>
											<span class="moreslide-text move">Move / Resize</span>
										</a>
										<a href="javascript: void(0)" class="love-move-object unlock">
											<i class="fa fa-lock" aria-hidden="true"></i>
											<i class="fa fa-arrows" aria-hidden="true"></i>
											<span class="moreslide-text lock">Lock</span>
											<span class="moreslide-text move">Move / Resize</span>
										</a>
									</li>
									<!-- <li>
											<a href="javascript: void(0)" class="crop-object">
												<i class="fa fa-crop" aria-hidden="true"></i><span
													class="moreslide-text">Crop</span>
											</a>
										</li> -->
									<li>
										<a href="javascript: void(0)" class="rotate-object">
											<i class="fa fa-repeat"></i><span class="moreslide-text">Rotate</span>
										</a>
									</li>
									<li>
										<a href="javascript: void(0)" class="replace-object">
											<span class="replace-image-icon">
												<img src="images/swap-default-1x.png" alt="">
											</span>
											<span class="moreslide-text">Replace</span>
										</a>
									</li>
									<li>
										<a href="javascript: void(0)" class="text-color-image">Color<span
												class="moreslide-text">Color</span></a>
									</li>
									<li>
										<a href="javascript: void(0)" class="dublicate-copy-image"><i
												class="fa fa-copy"></i>
											<span class="moreslide-text">Duplicate</span></a>
									</li>
									<li>
										<a href="javascript: void(0)" class="arrange-object">
											<i class="fa fa-layer-group"></i>
											<span class="moreslide-text">Arrange</span>
										</a>
									</li>
									<li>
										<a href="javascript: void(0)" class="delete-object">
											<i class="fa fa-trash"></i><span class="moreslide-text">Delete</span></a>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="admin-btn-cntrl">
						<div class="save-btn-container">
							<input type="hidden" name="card-type" id="card-type" value ='<?php echo $card_type; ?>' />
							<div class="save-btn-wrapper">
								<a href="javascript: void(0)" id= "updateOrder" class="save-btn save-for-user" data-step="14"
									data-intro="Please Click on this link to save your card">Update Order</a>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	require(["jquery","jquery/ui","Magento_Ui/js/modal/modal",'reviewcard','colorpicker','intro'],function($,uijquery,modal,reviewcard,colorpicker,introJs){
		$('#colorpicker-shadow, #colorpicker-outline, #colorpicker-full').colorpicker({
			parts: 'full',
			alpha: true,
			showOn: 'both',
			buttonColorize: true,
			showNoneButton: true
		});		
		$( "#updateOrder" ).on({click: function() {
		fabric.StaticCanvas.prototype._toObjectMethod = (function(toObjectMethod) {
			  return function(propertiesToInclude) {
				return fabric.util.object.extend(toObjectMethod.call(this, "toDatalessObject", propertiesToInclude), {
				  cardtype: this.cardtype
				});
			  };
		})(fabric.StaticCanvas.prototype._toObjectMethod);
			
		canvas.cardtype = $("#card-type").val();
			var requestUrl = $('#adminurl').val();
			var item_id = $('#item_id').val();
			var objectjson = JSON.stringify(canvas);
			var objectjsonback = JSON.stringify(canvasBack);
			   $.ajax({
					url: requestUrl,
					type: 'POST',
					data: { jsonobj: objectjson, objectjsonback: objectjsonback,  item_id : item_id } ,
					showLoader: true, //use for display loader
					 
					success: function (response) {
					showLoader: false //use for display loader
					   console.log(response)
					},
					error: function () {
						showLoader: false //use for display loader
						alert("error occured");
					}
				}); 
			} 
		});
		
			
	});
</script>