<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Magento\OfflinePayments\Block\Info\Purchaseorder
 */
?>
<?php 
$adminMainUrl =  $this->helper('Magento\Backend\Helper\Data')->getHomePageUrl(); 
$adminBaseUrl =  str_replace('admin/', '', $adminMainUrl);
?>
<div class="order-payment-method-name"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></div>
<table class="data-table admin__table-secondary">
    <tr>
        <th><?= $block->escapeHtml(__('PO Number')) ?>:</th>
        <td class="exist_po"><?= $block->escapeHtml($block->getInfo()->getPoNumber()) ?></td>
		<td><span class="po_update"><u><strong><?= $block->escapeHtml(__('Update')) ?></strong></u><span></td>
    </tr>
	<tr class="pobox" style="display:none;">
		<td><?= $block->escapeHtml(__('Update Po')) ?>:</td>
		<td class="pocoloumn"><input type="text" name="update_po" id="update_po" /> </td>
		<td><button class="btn button poupdate"><?= $block->escapeHtml(__('Update')) ?></button></td>
	</tr>
</table>
<script type="text/javascript">
    require(["jquery"],function($) {
        $(document).ready(function() {
			$('.po_update').click(function(){ 
				 $('.pobox').toggle();
			});
			
			$('.poupdate').click(function(){
				
				var po_number =  $('#update_po').val();
				
				if(po_number =='') {
					alert('Please enter po number!');
					return false;
				}
				
				var customurl = "<?php echo $adminBaseUrl.'pdfdesign/updatepo/index'?>";
				$.ajax({
					url: customurl,
					type: 'POST',
					dataType: 'json',
					data: {
						order_id: "<?php echo $this->getRequest()->getParam('order_id'); ?>",
						po_number:po_number
					},
					complete: function(response) {             
						$('.exist_po').html(po_number);
						$('.pobox').html('purchase order number has been updated');
					},
					error: function (xhr, status, errorThrown) {
						$('.pocoloumn').html('Error happens. Try again.');
					}
				});				
			});           
        });
    });
</script>